<a href="https://colab.research.google.com/github/locoxelcafe-byte/Pandas/blob/main/0_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
numeros = pd.Series([10, 20, 30, 40, 50])
numeros

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [2]:
promedio = numeros.mean()
print(f"El promedio es {promedio}")

El promedio es 30.0

In [3]:
total = numeros.sum()
total

np.int64(150)

In [4]:
maximo = numeros.max()
maximo

50

In [5]:
minimo = numeros.min()
minimo

10

In [6]:
import pandas as pd

In [152]:
df = pd.read_csv("/content/Precipitaciones.csv")
df.head(3)

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6

In [153]:
#type(df)

In [154]:
df.tail(2)

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
50,ZAMORA,53.0,112.0,6.8,63.7,19.8,54.2,3.1,9.6,78.5,55.3,29.0,50.3,535.3
51,ZARAGOZA,52.0,30.0,3.6,52.7,38.3,57.5,13.5,13.2,61.5,27.4,76.6,23.4,449.7

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      52 non-null     object
 1   enero       52 non-null     float64
 2   febrero     52 non-null     float64
 3   marzo       52 non-null     float64
 4   abril       52 non-null     float64
 5   mayo        52 non-null     float64
 6   junio       52 non-null     float64
 7   julio       52 non-null     float64
 8   agosto      52 non-null     float64
 9   septiembre  52 non-null     float64
 10  octubre     52 non-null     float64
 11  noviembre   52 non-null     float64
 12  diciembre   52 non-null     float64
 13  anual       52 non-null     float64
dtypes: float64(13), object(1)
memory usage: 5.8+ KB

In [13]:
df.describe()

,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,92.996154,78.632692,26.684615,64.500000,38.305769,54.182692,11.840385,17.178846,62.246154,54.373077,82.494231,76.192308,659.626923
std,57.127171,67.454280,31.473913,21.421942,29.079576,36.821635,13.256390,13.939496,28.581205,36.619785,91.689789,80.409042,352.905548
min,26.800000,2.300000,3.300000,3.500000,0.700000,1.100000,0.000000,0.000000,0.900000,1.000000,7.100000,1.800000,108.200000
25%,53.825000,32.825000,9.125000,53.950000,18.875000,26.325000,1.600000,4.850000,46.000000,29.825000,32.375000,22.075000,455.925000
50%,73.950000,62.600000,17.200000,62.700000,35.650000,50.400000,6.150000,16.500000,62.300000,46.550000,46.950000,47.950000,548.550000
75%,97.300000,102.550000,35.425000,77.625000,48.750000,78.025000,17.875000,26.550000,81.625000,74.500000,102.725000,107.000000,665.150000
max,261.900000,335.700000,209.800000,128.400000,149.500000,145.000000,46.800000,57.000000,122.800000,175.700000,384.600000,314.700000,1575.400000

In [14]:
df.shape

(52, 14)

In [15]:
df.columns

Index(['region', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
       'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre',
       'anual'],
      dtype='object')

In [155]:
import pandas as pd
serie = pd.Series([5, 10, 15, 20, 25])
serie

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [19]:
filtro = serie > 15
serie_filtrada = serie[filtro]
serie_filtrada

3    20
4    25
dtype: int64

In [20]:
filtro

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [21]:
serie2 = pd.Series(["banana", "pera", "melon", "manzana"])
serie2

0     banana
1       pera
2      melon
3    manzana
dtype: object

In [156]:
#type(serie2)

In [157]:
#type(serie2[0])

In [158]:
#print(dir(serie2))

In [159]:
#help(serie2.str)

In [26]:
filtro2 = serie2.str.contains("m")
filtro2

0    False
1    False
2     True
3     True
dtype: bool

In [27]:
filtro2

0    False
1    False
2     True
3     True
dtype: bool

In [28]:
serie2[filtro2]

2      melon
3    manzana
dtype: object

In [29]:
import pandas as pd

data = {"Id_producto": [1001, 1002, 1003, 1003],
        "Cantidad_vendida": [30, None, 25, 25],
        "Precio": [20.5, 15.0, None, 22.5]}

df = pd.DataFrame(data)
df

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [30]:
df.head()

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id_producto       4 non-null      int64
 1   Cantidad_vendida  3 non-null      float64
 2   Precio            3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

In [32]:
df.isnull()

   Id_producto  Cantidad_vendida  Precio
0        False             False   False
1        False              True   False
2        False             False    True
3        False             False   False

In [33]:
df.isnull().sum()

Id_producto         0
Cantidad_vendida    1
Precio              1
dtype: int64

In [34]:
df_eliminados = df.dropna()
df_eliminados

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
3         1003              25.0    22.5

In [35]:
valores_nuevos = {"Cantidad_vendida": 0, "Precio":df["Precio"].mean()}
df_rellenados = df.fillna(valores_nuevos)
df_rellenados

   Id_producto  Cantidad_vendida     Precio
0         1001              30.0  20.500000
1         1002               0.0  15.000000
2         1003              25.0  19.333333
3         1003              25.0  22.500000

In [36]:
df_rellenados["Cantidad_vendida"] = df_rellenados["Cantidad_vendida"].astype(int)
df_rellenados

   Id_producto  Cantidad_vendida     Precio
0         1001                30  20.500000
1         1002                 0  15.000000
2         1003                25  19.333333
3         1003                25  22.500000

In [37]:
df_unicos = df_rellenados.drop_duplicates()
df_unicos

   Id_producto  Cantidad_vendida     Precio
0         1001                30  20.500000
1         1002                 0  15.000000
2         1003                25  19.333333
3         1003                25  22.500000

In [38]:
df_unicos = df_rellenados.drop_duplicates(subset="Id_producto")
df_unicos

   Id_producto  Cantidad_vendida     Precio
0         1001                30  20.500000
1         1002                 0  15.000000
2         1003                25  19.333333

In [39]:
serie = pd.Series([10, 20, 30, 40, 50])
serie

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [40]:
serie[0] = serie[0] + 10
serie

0    20
1    20
2    30
3    40
4    50
dtype: int64

In [41]:
serie = serie + 10
serie

0    30
1    30
2    40
3    50
4    60
dtype: int64

In [42]:
serie = serie * 2
serie

0     60
1     60
2     80
3    100
4    120
dtype: int64

In [160]:
df = pd.read_csv("/content/Precipitaciones.csv")
df.head(2)

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5

In [44]:
serie = df["region"]
serie.head()

0    A CORUNA
1    ALBACETE
2    ALICANTE
3     ALMERIA
4       ARABA
Name: region, dtype: object

In [45]:
datos = [10, 20, 30, 40, 50]
serie2 = pd.Series(datos)
serie2

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [46]:
indices = ["a", "b", "c", "d", "e"]
serie2 = pd.Series(datos,indices)
serie2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [47]:
serie2["b"]

np.int64(20)

In [161]:
#type(serie2)

In [162]:
#type(serie2["b"])

In [50]:
capitales = {"España": "Madrid", "Perú": "Lima", "Argentina": "Buenos Aires"}
serie3 = pd.Series(capitales)
serie3

España             Madrid
Perú                 Lima
Argentina    Buenos Aires
dtype: object

In [51]:
serie3["Perú"]

'Lima'

In [52]:
datos = {"nombre": ["Pedro", "Juan", "Lorena"], "edad": [25, 39, 33]}
datos

{'nombre': ['Pedro', 'Juan', 'Lorena'], 'edad': [25, 39, 33]}

In [53]:
df = pd.DataFrame(datos)
df

   nombre  edad
0   Pedro    25
1    Juan    39
2  Lorena    33

In [163]:
#type(df)

In [55]:
df["nombre"]

0     Pedro
1      Juan
2    Lorena
Name: nombre, dtype: object

In [164]:
#type(df.nombre)

In [59]:
import pandas as pd
ruta = '/content/medallas.csv'
df = pd.read_csv(ruta)
df

     Oro  Plata  Bronce  Total          Pais
0    NaN    1.0     2.0      3     Argentina
1    NaN    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    NaN    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   NaN    1.0     NaN      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    NaN     2.0      5    Uzbekistan
92   1.0    3.0     NaN      4     Venezuela

[93 rows x 5 columns]

In [60]:
df.shape

(93, 5)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     object
dtypes: float64(3), int64(1), object(1)
memory usage: 3.8+ KB

In [62]:
df.describe()

             Oro      Plata     Bronce       Total
count  65.000000  69.000000  76.000000   93.000000
mean    4.400000   4.768116   4.934211   10.548387
std     7.633806   7.276362   6.261705   18.897617
min     1.000000   1.000000   1.000000    1.000000
25%     1.000000   1.000000   1.000000    2.000000
50%     2.000000   2.000000   2.000000    4.000000
75%     3.000000   5.000000   5.250000    8.000000
max    39.000000  41.000000  33.000000  113.000000

In [63]:
df.isnull().sum()

Oro       28
Plata     24
Bronce    17
Total      0
Pais       0
dtype: int64

In [64]:
df.fillna(0, inplace=True)
df

     Oro  Plata  Bronce  Total          Pais
0    0.0    1.0     2.0      3     Argentina
1    0.0    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    0.0    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   0.0    1.0     0.0      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    0.0     2.0      5    Uzbekistan
92   1.0    3.0     0.0      4     Venezuela

[93 rows x 5 columns]

In [65]:
df["Oro"] = df["Oro"].astype(int)
df["Plata"] = df["Plata"].astype(int)
df["Bronce"] = df["Bronce"].astype(int)
df

    Oro  Plata  Bronce  Total          Pais
0     0      1       2      3     Argentina
1     0      2       2      4       Armenia
2    17      7      22     46     Australia
3     1      1       5      7       Austria
4     0      3       4      7    Azerbaijan
..  ...    ...     ...    ...           ...
88    0      1       0      1  Turkmenistan
89    2      1       1      4        Uganda
90    1      6      12     19       Ukraine
91    3      0       2      5    Uzbekistan
92    1      3       0      4     Venezuela

[93 rows x 5 columns]

In [66]:
top_3_oro = df.sort_values('Oro', ascending=False).head(3)
top_3_oro

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
46   27     14      17     58                       Japon

In [67]:
filtro = df['Total'] > 10
mas_de_10_medallas = df[filtro]
mas_de_10_medallas.sort_values('Total', ascending=False)

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC
34   22     21      22     65                Gran Bretana
46   27     14      17     58                       Japon
2    17      7      22     46                   Australia
32    1     11      16     37                     Germany
60    1     12      14     36                 Netherlands
30    1     12      11     33                      France
14    7      6      11     24                      Canada
11    7      6       8     21                      Brazil
90    1      6      12     19                     Ukraine
81    3      8       6     17                       Spain
19    7      3       5     15                        Cuba
66    4      5       5     14                      Poland
83    3      4       6     13                 Switzerland
87    2      2       9     13                      Turkey
15    2      4       6     12              Chinese Taipei
20    4      4       3     11              Czech Republic
21    3      4       4     11                     Denmark

In [68]:
ruta_excel = '/content/Compras_desde_ads.xlsx'
ruta_xml = '/content/Valores+de+acciones.xml'

In [69]:
df1 = pd.read_excel(ruta_excel)
df1.head()

   Id_usuario     Genero  Edad  Salario_estimado  Comprado
0    15624510  Masculino    19             19000         0
1    15810944  Masculino    35             20000         0
2    15668575   Femenino    26             43000         0
3    15603246   Femenino    27             57000         0
4    15804002  Masculino    19             76000         0

In [70]:
df2 = pd.read_xml(ruta_xml)
df2.head(5)

         date closingValue
0  01-05-2023        25,05
1  02-05-2023        24,45
2  03-05-2023        24,45
3  04-05-2023        23,98
4  05-05-2023        24,56

In [71]:
numeros = {
    'romanos': ['I', 'II', 'III', 'IV'],
    'arabigos': [1, 2, 3, 4],
    'texto': ['uno', 'dos', 'tres', 'cuatro']
}

In [72]:
df = pd.DataFrame(numeros)
df

  romanos  arabigos   texto
0       I         1     uno
1      II         2     dos
2     III         3    tres
3      IV         4  cuatro

In [73]:
df['Fechas'] = pd.Series(pd.date_range('20240101', periods=4))
df

  romanos  arabigos   texto     Fechas
0       I         1     uno 2024-01-01
1      II         2     dos 2024-01-02
2     III         3    tres 2024-01-03
3      IV         4  cuatro 2024-01-04

In [74]:
df = pd.DataFrame({
    'Col1': [100, 200, 300],
    'Col2': [400, 500, 600],
    'Col3': [700, 800, 900]
}, index=['fila1', 'fila2', 'fila3'])

df

       Col1  Col2  Col3
fila1   100   400   700
fila2   200   500   800
fila3   300   600   900

In [75]:
df.loc['fila1']

Col1    100
Col2    400
Col3    700
Name: fila1, dtype: int64

In [76]:
type(df.loc['fila1'])

pandas.core.series.Series

In [77]:
df.loc[['fila1', 'fila3']]

       Col1  Col2  Col3
fila1   100   400   700
fila3   300   600   900

In [165]:
#type(df.loc[['fila1', 'fila3']])

In [79]:
df.loc['fila2':'fila3']

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [80]:
df.loc[[False, True, False]]

       Col1  Col2  Col3
fila2   200   500   800

In [81]:
df.loc[df['Col1'] > 150]

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [82]:
df.loc[:, ['Col1', 'Col2']]

       Col1  Col2
fila1   100   400
fila2   200   500
fila3   300   600

In [83]:
df.iloc[0]

Col1    100
Col2    400
Col3    700
Name: fila1, dtype: int64

In [84]:
df.iloc[:, [0,1]]

       Col1  Col2
fila1   100   400
fila2   200   500
fila3   300   600

In [85]:
df.iloc[1:3]

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [86]:
import pandas as pd

df1 = pd.DataFrame({'Salario': [30000, 45000, 38000],
                    'Antigüedad': [9, 13, 12]},
                   index=[1, 2, 3])
df2 = pd.DataFrame({'Ciudad': ['Madrid', 'Barcelona', 'Valencia'],
                    'Jerarquía': ['Baja', 'Alta', 'Media']},
                   index=[1, 2, 4])

In [87]:
df1

   Salario  Antigüedad
1    30000           9
2    45000          13
3    38000          12

In [88]:
df2

      Ciudad Jerarquía
1     Madrid      Baja
2  Barcelona      Alta
4   Valencia     Media

In [89]:
df_unido = df1.join(df2)
df_unido

   Salario  Antigüedad     Ciudad Jerarquía
1    30000           9     Madrid      Baja
2    45000          13  Barcelona      Alta
3    38000          12        NaN       NaN

In [90]:
df_unido = df1.join(df2, how='inner')
df_unido

   Salario  Antigüedad     Ciudad Jerarquía
1    30000           9     Madrid      Baja
2    45000          13  Barcelona      Alta

In [91]:
df1 = pd.DataFrame({'Nombre': ["Juan", "Gabriela", "Elena"], 'Edad': [23, 31, 21]})
df1

     Nombre  Edad
0      Juan    23
1  Gabriela    31
2     Elena    21

In [92]:
df2 = pd.DataFrame({'Nombre': ["Carmela", "Max", "Laura"], 'Edad': [34, 25, 29]})
df2

    Nombre  Edad
0  Carmela    34
1      Max    25
2    Laura    29

In [93]:
df_cancatenado = pd.concat([df1, df2])
df_cancatenado

     Nombre  Edad
0      Juan    23
1  Gabriela    31
2     Elena    21
0   Carmela    34
1       Max    25
2     Laura    29

In [94]:
df_cancatenado2 = pd.concat([df1, df2], axis=1)
df_cancatenado2

     Nombre  Edad   Nombre  Edad
0      Juan    23  Carmela    34
1  Gabriela    31      Max    25
2     Elena    21    Laura    29

In [95]:
df_cancatenado = pd.concat([df1, df2], ignore_index=True)
df_cancatenado

     Nombre  Edad
0      Juan    23
1  Gabriela    31
2     Elena    21
3   Carmela    34
4       Max    25
5     Laura    29

In [96]:
df_cancatenado = pd.concat([df1, df2], keys=['df1', 'df2'])
df_cancatenado

         Nombre  Edad
df1 0      Juan    23
    1  Gabriela    31
    2     Elena    21
df2 0   Carmela    34
    1       Max    25
    2     Laura    29

In [97]:
df_cancatenado = pd.concat([df1, df2], keys=['enero', 'febrero'])
df_cancatenado

             Nombre  Edad
enero   0      Juan    23
        1  Gabriela    31
        2     Elena    21
febrero 0   Carmela    34
        1       Max    25
        2     Laura    29

In [98]:
fechas = pd.Series(pd.date_range('20240101', periods=6))
fechas

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
dtype: datetime64[ns]

In [99]:
type(fechas[0])

pandas._libs.tslibs.timestamps.Timestamp

In [100]:
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='D'))
fechas

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
dtype: datetime64[ns]

In [101]:
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='D'))
fechas

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
dtype: datetime64[ns]

In [102]:
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='M'))
fechas

/tmp/ipykernel_879/661938073.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fechas = pd.Series(pd.date_range('20240101', periods=6, freq='M'))

0   2024-01-31
1   2024-02-29
2   2024-03-31
3   2024-04-30
4   2024-05-31
5   2024-06-30
dtype: datetime64[ns]

In [103]:
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='Y'))
fechas

/tmp/ipykernel_879/2898099646.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  fechas = pd.Series(pd.date_range('20240101', periods=6, freq='Y'))

0   2024-12-31
1   2025-12-31
2   2026-12-31
3   2027-12-31
4   2028-12-31
5   2029-12-31
dtype: datetime64[ns]

In [104]:
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='H'))
fechas

/tmp/ipykernel_879/3246372151.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  fechas = pd.Series(pd.date_range('20240101', periods=6, freq='H'))

0   2024-01-01 00:00:00
1   2024-01-01 01:00:00
2   2024-01-01 02:00:00
3   2024-01-01 03:00:00
4   2024-01-01 04:00:00
5   2024-01-01 05:00:00
dtype: datetime64[ns]

In [105]:
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='MIN'))
fechas

/tmp/ipykernel_879/898040804.py:1: FutureWarning: 'MIN' is deprecated and will be removed in a future version, please use 'min' instead.
  fechas = pd.Series(pd.date_range('20240101', periods=6, freq='MIN'))

0   2024-01-01 00:00:00
1   2024-01-01 00:01:00
2   2024-01-01 00:02:00
3   2024-01-01 00:03:00
4   2024-01-01 00:04:00
5   2024-01-01 00:05:00
dtype: datetime64[ns]

In [106]:
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='S'))
fechas

/tmp/ipykernel_879/3061747196.py:1: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  fechas = pd.Series(pd.date_range('20240101', periods=6, freq='S'))

0   2024-01-01 00:00:00
1   2024-01-01 00:00:01
2   2024-01-01 00:00:02
3   2024-01-01 00:00:03
4   2024-01-01 00:00:04
5   2024-01-01 00:00:05
dtype: datetime64[ns]

In [107]:
ruta = '/content/Mercado+de+Valores+España.csv'
df = pd.read_csv(ruta)
df

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,02/01/2019,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,03/01/2019,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,04/01/2019,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,07/01/2019,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,08/01/2019,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409
...,...,...,...,...,...,...,...,...,...,...
8570,VIS,09/12/2019,48.70,48.76,40236,1958325.66,48.70,48.96,48.44,48.6710
8571,VIS,10/12/2019,48.16,48.70,60198,2895965.78,48.16,48.74,47.70,48.1201
8572,VIS,11/12/2019,47.96,48.16,63000,3012462.12,47.96,48.42,47.52,47.8169
8573,VIS,12/12/2019,48.42,47.96,50218,2429199.80,48.42,48.66,47.76,48.3731
8574,VIS,13/12/2019,48.64,48.42,62427,3038685.10,48.64,49.18,48.12,48.6758

In [108]:
df['Fecha'][0]

'02/01/2019'

In [166]:
#type(df['Fecha'][0])

In [110]:
df['Fecha'] = pd.to_datetime(df['Fecha'], format='%d/%m/%Y')
df

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,2019-01-02,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,2019-01-03,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,2019-01-04,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,2019-01-07,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,2019-01-08,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409
...,...,...,...,...,...,...,...,...,...,...
8570,VIS,2019-12-09,48.70,48.76,40236,1958325.66,48.70,48.96,48.44,48.6710
8571,VIS,2019-12-10,48.16,48.70,60198,2895965.78,48.16,48.74,47.70,48.1201
8572,VIS,2019-12-11,47.96,48.16,63000,3012462.12,47.96,48.42,47.52,47.8169
8573,VIS,2019-12-12,48.42,47.96,50218,2429199.80,48.42,48.66,47.76,48.3731
8574,VIS,2019-12-13,48.64,48.42,62427,3038685.10,48.64,49.18,48.12,48.6758

In [111]:
df['Fecha'][0]

Timestamp('2019-01-02 00:00:00')

In [167]:
#type(df['Fecha'][0])

In [113]:
df['Fecha'][44]

Timestamp('2019-03-05 00:00:00')

In [114]:
anio = df['Fecha'][44].year
anio

2019

In [115]:
mes = df['Fecha'][44].month
mes

3

In [116]:
df_mas_5_dias = df['Fecha'] + pd.Timedelta(days=5)
df_mas_5_dias

0      2019-01-07
1      2019-01-08
2      2019-01-09
3      2019-01-12
4      2019-01-13
          ...
8570   2019-12-14
8571   2019-12-15
8572   2019-12-16
8573   2019-12-17
8574   2019-12-18
Name: Fecha, Length: 8575, dtype: datetime64[ns]

In [117]:
df1 = pd.DataFrame({'ID': [1, 2, 3],
                    'Nombre': ['Ana', 'Luis', 'Carlos']})
df2 = pd.DataFrame({'ID': [1, 2, 4],
                    'Edad': [25, 30, 22]})

In [118]:
df1

   ID  Nombre
0   1     Ana
1   2    Luis
2   3  Carlos

In [119]:
df2

   ID  Edad
0   1    25
1   2    30
2   4    22

In [120]:
df_combinado = pd.merge(df1, df2, on='ID')
df_combinado

   ID Nombre  Edad
0   1    Ana    25
1   2   Luis    30

In [121]:
df_combinado = pd.merge(df1, df2, on='ID', how='inner')
df_combinado

   ID Nombre  Edad
0   1    Ana    25
1   2   Luis    30

In [122]:
df_combinado = pd.merge(df1, df2, on='ID', how='outer')
df_combinado

   ID  Nombre  Edad
0   1     Ana  25.0
1   2    Luis  30.0
2   3  Carlos   NaN
3   4     NaN  22.0

In [123]:
df_combinado = pd.merge(df1, df2, on='ID', how='left')
df_combinado

   ID  Nombre  Edad
0   1     Ana  25.0
1   2    Luis  30.0
2   3  Carlos   NaN

In [124]:
df_combinado = pd.merge(df1, df2, on='ID', how='right')
df_combinado

   ID Nombre  Edad
0   1    Ana    25
1   2   Luis    30
2   4    NaN    22

In [125]:
df_indexado = pd.merge(df1, df2, left_index=True, right_index=True)
df_indexado

   ID_x  Nombre  ID_y  Edad
0     1     Ana     1    25
1     2    Luis     2    30
2     3  Carlos     4    22

In [168]:
ruta = '/content/Top-Películas (1).csv'
df = pd.read_csv(ruta)
df.head(2)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97

In [127]:
df_ordenado = df.sort_values(by='rating')
df_ordenado.head(10)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
2531,2531,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Drama,7.6,0.0,0.00
2530,2530,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Crimen,7.6,0.0,0.00
2529,2529,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Acción,7.6,0.0,0.00
2528,2528,998.0,The Invisible Man,James Whale,1933.0,71.0,Ciencia Ficción,7.6,87.0,0.00
2495,2495,986.0,From Here to Eternity,Fred Zinnemann,1953.0,118.0,Guerra,7.6,85.0,30.50
2496,2496,987.0,50/50,Jonathan Levine,2011.0,100.0,Comedia,7.6,72.0,35.01
2497,2497,987.0,50/50,Jonathan Levine,2011.0,100.0,Drama,7.6,72.0,35.01
2482,2482,981.0,After Hours,Martin Scorsese,1985.0,97.0,Drama,7.6,90.0,10.60
2483,2483,982.0,Sabrina,Billy Wilder,1954.0,113.0,Comedia,7.6,72.0,0.00
2484,2484,982.0,Sabrina,Billy Wilder,1954.0,113.0,Drama,7.6,72.0,0.00

In [169]:
df_ordenado = df.sort_values(by='rating', ascending=False)
df_ordenado.head(2)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97

In [170]:
df_ordenado = df.sort_values(by=['rating', 'recaudación(M)'], ascending=False)
df_ordenado.head(2)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97

In [171]:
df_agrupado = df.groupby('género')['rating'].mean()
df_agrupado.head(3)

género
Acción       7.987255
Animación    7.943902
Aventura     7.980435
Name: rating, dtype: float64

In [131]:
df_agrupado = df.groupby('año')['recaudación(M)'].sum()

In [172]:
df_agrupado.sort_values(ascending=False).head(3)

género
Guerra     8.053191
Western    8.006250
Crimen     7.993500
Name: rating, dtype: float64

In [133]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}

df = pd.DataFrame(data)
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    22   Valencia
3    Sara    27     Bilbao

In [134]:
df['Salario'] = [30000, 45000, 38000, 32000]
df

   Nombre  Edad     Ciudad  Salario
0     Ana    25     Madrid    30000
1    Luis    30  Barcelona    45000
2  Carlos    22   Valencia    38000
3    Sara    27     Bilbao    32000

In [135]:
df['Salario'] = df['Salario'] + 2000
df

   Nombre  Edad     Ciudad  Salario
0     Ana    25     Madrid    32000
1    Luis    30  Barcelona    47000
2  Carlos    22   Valencia    40000
3    Sara    27     Bilbao    34000

In [136]:
nombres = df['Nombre']
nombres

0       Ana
1      Luis
2    Carlos
3      Sara
Name: Nombre, dtype: object

In [137]:
mayores_25 = df[df['Edad'] > 25]
mayores_25

  Nombre  Edad     Ciudad  Salario
1   Luis    30  Barcelona    47000
3   Sara    27     Bilbao    34000

In [138]:
edades = df['Edad']
edades

0    25
1    30
2    22
3    27
Name: Edad, dtype: int64

In [139]:
mayores_25 = df[edades > 25]
mayores_25

  Nombre  Edad     Ciudad  Salario
1   Luis    30  Barcelona    47000
3   Sara    27     Bilbao    34000

In [173]:
#type(df)

In [174]:
#type(edades)

In [175]:
#type(mayores_25)

In [176]:
ruta = '/content/Datos_Ventas_Tienda.csv'
df_ventas = pd.read_csv(ruta)
df_ventas.head(3)

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0  1/17/2023  Electrónic         7              200         1400
1   9/1/2023  Electrónic         8              200         1600
2  7/29/2023    Juguetes         3               30           90

In [177]:
ruta2 = '/content/Datos_Ventas_Tienda2.csv'
df_ventas2 = pd.read_csv(ruta2)
df_ventas2.head(2)

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0  8/25/2023  Electrónic         5              200         1000
1  8/14/2023   Alimentos         9               10           90

In [181]:
df = pd.concat([df_ventas, df_ventas2], ignore_index=True)
df.tail(2)

          Fecha    Producto  Cantidad  Precio Unitario  Total Venta
1048  8/20/2023  Electrónic         6              200         1200
1049  7/21/2023    Juguetes         3               30           90

In [183]:
df['Fecha'] = pd.to_datetime(df['Fecha'])
df.head(2)

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0 2023-01-17  Electrónic         7              200         1400
1 2023-09-01  Electrónic         8              200         1600

In [147]:
# Producto más vendido
producto_mas_vendido = df.groupby('Producto')['Cantidad'].sum()
producto_mas_vendido = producto_mas_vendido.sort_values(ascending=False)
producto_mas_vendido.head(1)

Producto
Alimentos    1262
Name: Cantidad, dtype: int64

In [184]:
meses = []
for f in df['Fecha']:
    meses.append(f.month)

df['Meses'] = meses
df.head(3)

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta  Meses
0 2023-01-17  Electrónic         7              200         1400      1
1 2023-09-01  Electrónic         8              200         1600      9
2 2023-07-29    Juguetes         3               30           90      7

In [149]:
ventas_por_mes = df.groupby('Meses')['Total Venta'].sum().sort_values(ascending=False)
ventas_por_mes.head(1)

Meses
8    45090
Name: Total Venta, dtype: int64

In [150]:
ventas_por_categoria = df.groupby('Producto')['Total Venta'].sum()
ventas_por_categoria

Producto
Alimentos      12620
Electrónic    244000
Juguetes       33390
Libros         20840
Ropa           56400
Name: Total Venta, dtype: int64

In [151]:
df.to_csv('Resumen_ventas.csv')